
const countryCode = {
    afghanistan: 'af',
    albania: 'al',
    algeria: 'dz',
    'american samoa': 'as',
    andorra: 'ad',
    angola: 'ao',
    anguilla: 'ai',
    antarctica: 'aq',
    'antigua and barbuda': 'ag',
    argentina: 'ar',
    armenia: 'am',
    aruba: 'aw',
    australia: 'au',
    austria: 'at',
    azerbaijan: 'az',
    bahamas: 'bs',
    bahrain: 'bh',
    bangladesh: 'bd',
    barbados: 'bb',
    belarus: 'by',
    belgium: 'be',
    belize: 'bz',
    benin: 'bj',
    bermuda: 'bm',
    bhutan: 'bt',
    bolivia: 'bo',
    'bosnia and herzegovina': 'ba',
    botswana: 'bw',
    brazil: 'br',
    'british indian ocean territory': 'io',
    'british virgin islands': 'vg',
    brunei: 'bn',
    bulgaria: 'bg',
    'burkina faso': 'bf',
    burundi: 'bi',
    cambodia: 'kh',
    cameroon: 'cm',
    canada: 'ca',
    'cape verde': 'cv',
    'cayman islands': 'ky',
    'central african republic': 'cf',
    chad: 'td',
    chile: 'cl',
    china: 'cn',
    'christmas island': 'cx',
    'cocos islands': 'cc',
    colombia: 'co',
    comoros: 'km',
    'cook islands': 'ck',
    'costa rica': 'cr',
    croatia: 'hr',
    cuba: 'cu',
    curacao: 'cw',
    cyprus: 'cy',
    'czech republic': 'cz',
    'democratic republic of the congo': 'cd',
    denmark: 'dk',
    djibouti: 'dj',
    dominica: 'dm',
    'dominican republic': 'do',
    'east timor': 'tl',
    ecuador: 'ec',
    egypt: 'eg',
    'el salvador': 'sv',
    'equatorial guinea': 'gq',
    eritrea: 'er',
    estonia: 'ee',
    ethiopia: 'et',
    'falkland islands': 'fk',
    'faroe islands': 'fo',
    fiji: 'fj',
    finland: 'fi',
    france: 'fr',
    'french polynesia': 'pf',
    gabon: 'ga',
    gambia: 'gm',
    georgia: 'ge',
    germany: 'de',
    ghana: 'gh',
    gibraltar: 'gi',
    greece: 'gr',
    greenland: 'gl',
    grenada: 'gd',
    guam: 'gu',
    guatemala: 'gt',
    guernsey: 'gg',
    guinea: 'gn',
    'guinea-bissau': 'gw',
    guyana: 'gy',
    haiti: 'ht',
    honduras: 'hn',
    'hong kong': 'hk',
    hungary: 'hu',
    iceland: 'is',
    india: 'in',
    indonesia: 'id',
    iran: 'ir',
    iraq: 'iq',
    ireland: 'ie',
    'isle of man': 'im',
    israel: 'il',
    italy: 'it',
    'ivory coast': 'ci',
    jamaica: 'jm',
    japan: 'jp',
    jersey: 'je',
    jordan: 'jo',
    kazakhstan: 'kz',
    kenya: 'ke',
    kiribati: 'ki',
    kosovo: 'xk',
    kuwait: 'kw',
    kyrgyzstan: 'kg',
    laos: 'la',
    latvia: 'lv',
    lebanon: 'lb',
    lesotho: 'ls',
    liberia: 'lr',
    libya: 'ly',
    liechtenstein: 'li',
    lithuania: 'lt',
    luxembourg: 'lu',
    macau: 'mo',
    macedonia: 'mk',
    madagascar: 'mg',
    malawi: 'mw',
    malaysia: 'my',
    maldives: 'mv',
    mali: 'ml',
    malta: 'mt',
    'marshall islands': 'mh',
    mauritania: 'mr',
    mauritius: 'mu',
    mayotte: 'yt',
    mexico: 'mx',
    micronesia: 'fm',
    moldova: 'md',
    monaco: 'mc',
    mongolia: 'mn',
    montenegro: 'me',
    montserrat: 'ms',
    morocco: 'ma',
    mozambique: 'mz',
    myanmar: 'mm',
    namibia: 'na',
    nauru: 'nr',
    nepal: 'np',
    netherlands: 'nl',
    'netherlands antilles': 'an',
    'new caledonia': 'nc',
    'new zealand': 'nz',
    nicaragua: 'ni',
    niger: 'ne',
    nigeria: 'ng',
    niue: 'nu',
    'north korea': 'kp',
    'northern mariana islands': 'mp',
    norway: 'no',
    oman: 'om',
    pakistan: 'pk',
    palau: 'pw',
    palestine: 'ps',
    panama: 'pa',
    'papua new guinea': 'pg',
    paraguay: 'py',
    peru: 'pe',
    philippines: 'ph',
    pitcairn: 'pn',
    poland: 'pl',
    portugal: 'pt',
    'puerto rico': 'pr',
    qatar: 'qa',
    'republic of the congo': 'cg',
    reunion: 're',
    romania: 'ro',
    russia: 'ru',
    rwanda: 'rw',
    'saint barthelemy': 'bl',
    'saint helena': 'sh',
    'saint kitts and nevis': 'kn',
    'saint lucia': 'lc',
    'saint martin': 'mf',
    'saint pierre and miquelon': 'pm',
    'saint vincent and the grenadines': 'vc',
    samoa: 'ws',
    'san marino': 'sm',
    'sao tome and principe': 'st',
    'saudi arabia': 'sa',
    czechia: 'cz',
    senegal: 'sn',
    serbia: 'rs',
    seychelles: 'sc',
    'sierra leone': 'sl',
    singapore: 'sg',
    'sint maarten': 'sx',
    slovakia: 'sk',
    slovenia: 'si',
    'solomon islands': 'sb',
    somalia: 'so',
    'south africa': 'za',
    's. korea': 'kr',
    'south sudan': 'ss',
    spain: 'es',
    'sri lanka': 'lk',
    sudan: 'sd',
    suriname: 'sr',
    'svalbard and jan mayen': 'sj',
    swaziland: 'sz',
    sweden: 'se',
    switzerland: 'ch',
    syria: 'sy',
    taiwan: 'tw',
    tajikistan: 'tj',
    tanzania: 'tz',
    thailand: 'th',
    togo: 'tg',
    tokelau: 'tk',
    tonga: 'to',
    'trinidad and tobago': 'tt',
    tunisia: 'tn',
    turkey: 'tr',
    turkmenistan: 'tm',
    'turks and caicos islands': 'tc',
    tuvalu: 'tv',
    'u.s. virgin islands': 'vi',
    uganda: 'ug',
    ukraine: 'ua',
    'united arab emirates': 'ae',
    'uk': 'gb',
    'usa': 'us',
    uruguay: 'uy',
    uzbekistan: 'uz',
    vanuatu: 'vu',
    vatican: 'va',
    venezuela: 've',
    vietnam: 'vn',
    'wallis and futuna': 'wf',
    'western sahara': 'eh',
    yemen: 'ye',
    zambia: 'zm',
    zimbabwe: 'zw',
    martinique: 'mq',
    guadeloupe: 'gp',
    drc: 'cd',
    'french guiana': 'gf',
    'channel islands': 'je',
    eswatini: 'sz'
}

export default countryCode;